platform :ios, '13.0'
use_frameworks!

target 'Example' do
    pod 'JNAvatarWithInitials', :path => '../'
end


# Update All Pods to have minimum IOS version to 13.0
post_install do |installer|
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
